apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: fireflyiii/core
    newTag: version-6.2.10
  - name: fireflyiii/data-importer
    newTag: version-1.6.1