apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: fireflyiii/core
    newTag: version-6.1.7
  - name: fireflyiii/data-importer
    newTag: version-1.3.8

patches:
  - target:
      kind: PersistentVolumeClaim
      name: firefly-iii
    patch: |-
      - op: replace
        path: /spec/resources/requests/storage
        value: "1Ti"
  - target:
      kind: PersistentVolumeClaim
      name: mariabackup
    patch: |-
      - op: replace
        path: /spec/resources/requests/storage
        value: "1Ti"

