apiVersion: v1
kind: Secret
metadata:
  name: firefly-iii
  annotations:
    avp.kubernetes.io/path: "k8s-secrets/data/firefly"    
stringData:
  access_token: <access_token>
  app_key: <app_key>
  mail_host: <mail_host>
  mail_password: <mail_password>
  mail_from: <mail_from>
  mail_username: <mail_username>