apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: firefly-iii-importer
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: cephfs-hdd-r2-squid

